### ISSUE TITLE
Fork or contribute?

### ISSUE THREAD

**Issue by coolreader18** [notriddle/rust-timsort#1]
I'm interested in adding new functionality to this crate to use it in [RustPython](https://github.com/RustPython/RustPython); are you still interested in still maintaining this? If not, I'd be happy to just maintain it separately as [RustPython/rust-timsort](https://github.com/RustPython/rust-timsort).

**Comment by notriddle** [comment]
I'm not interested in maintaining this. You should fork.

In the mean time, I'm also going to archive this repository.
